export const constants = {
  // GAME
  START_GAME: "GAME_START_GAME",
  PLAYER_VALUE_CHANGE: "GAME_PLAYER_VALUE_CHANGE",
  // TOON
  CHANGE_POSITION: "TOON_CHANGE_POSITION",
  CHANGE_DIRECTION: "TOON_CHANGE_DIRECTION"
};
