export const constants = {
  // GAME
  START_GAME: "GAME_START_GAME",
  PLAYER_VALUE_CHANGE: "GAME_PLAYER_VALUE_CHANGE",
  INPUT_VALUE_CHANGE: "GAME_INPUT_VALUE_CHANGE",
  // BOARD
  GET_WORD_LIST: "BOARD_GET_WORD_LIST",
  CHANGE_LAST_KEY_PRESS: "BOARD_CHANGE_LAST_KEY_PRESS",
  CHANGE_ACTIVE_WORD: "BOARD_CHANGE_ACTIVE_WORD",
  KEY_PRESS_SUCCESS: "BOARD_KEY_PRESS_SUCCESS",
  KEY_PRESS_FAILURE: "BOARD_KEY_PRESS_FAILURE"
};
